src/atomist.config.ts
src/handlers/commands/editors/toclient/ghub.ts
src/handlers/events/delivery/OnVerifiedStatus.ts
src/software-delivery-machine/blueprint/describeRunningServices.ts
src/software-delivery-machine/blueprint/diffRendering.ts
src/software-delivery-machine/blueprint/lifecycleHelpers.ts
src/software-delivery-machine/blueprint/offerPromotion.ts
test/diffRenderingTest.ts

there are some files here that very need moved out of blueprint
... but take a look at the messages in #losgatos1

render the commits on the diff. Show them in promotion

---

src/handlers/events/delivery/deploy/DeployFromLocalOnFingerprint.ts
src/handlers/events/delivery/deploy/deploy.ts
src/handlers/events/delivery/deploy/pcf/CommandLineCloudFoundryDeployer.ts
src/handlers/events/delivery/log/ProgressLog.ts
src/handlers/events/delivery/phases/productionDeployPhases.ts
src/software-delivery-machine/blueprint/deploy/offerPromotion.ts
src/util/diffRendering.ts
test/handlers/events/delivery/PhasesTest.ts

It never didn't work, given the right environment, but it did fail to return something that automation-client likes
i made an issue in the client to please accept undefined
and there are error handling tweaks in here as I struggled to get it to tell me what was wrong

Fix promote

---

src/atomist.config.ts
src/handlers/commands/editors/toclient/ghub.ts
src/handlers/events/delivery/deploy/pcf/CommandLineCloudFoundryDeployer.ts
src/software-delivery-machine/SpringPCFSoftwareDeliveryMachine.ts
src/software-delivery-machine/blueprint/deploy/dispose.ts

this is specific to PCF and our spaces
It deletes the repo and deployments in both  spaces

Dispose handler

---

src/handlers/events/delivery/deploy/k8s/RequestDeployOnSuccessStatus.ts
src/software-delivery-machine/blueprint/deploy/dispose.ts
src/software-delivery-machine/commands/editors/k8s/addK8sSpec.ts

change the dispose command to work for k8s
This is not general; it needs to work for both SDMs, but I don't want to work any more on it right now, and it'll be better

Undeploy for k8s

---

src/atomist.config.ts
src/blueprint/SoftwareDeliveryMachine.ts
src/common/phases/Phases.ts
src/common/phases/gitHubContext.ts
src/handlers/events/delivery/build/FindArtifactOnImageLinked.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/deploy/deploy.ts
src/handlers/events/delivery/deploy/k8s/NoticeK8sDeployCompletion.ts
src/handlers/events/delivery/deploy/k8s/RequestDeployOnSuccessStatus.ts
src/handlers/events/delivery/deploy/pcf/CloudFoundryTarget.ts
src/handlers/events/delivery/phases/httpServicePhases.ts
src/handlers/events/delivery/phases/libraryPhases.ts
src/handlers/events/delivery/phases/npmPhases.ts
src/handlers/events/delivery/scan/review/OnPendingScanStatus.ts
src/handlers/events/delivery/verify/OnEndpointStatus.ts
src/handlers/events/delivery/verify/common/lookFor200OnEndpointRootGet.ts
src/software-delivery-machine/blueprint/build/K8sBuildOnScanSuccess.ts
src/software-delivery-machine/blueprint/build/localBuildOnScanSuccessStatus.ts
src/software-delivery-machine/blueprint/deploy/describeRunningServices.ts
src/software-delivery-machine/blueprint/deploy/dispose.ts
src/software-delivery-machine/blueprint/deploy/k8sDeploy.ts
test/handlers/events/delivery/PhasesTest.ts

This moves toward using PlannedPhase (now a class) instead of context strings, which lets us configure the messaging for each one.
Not all the messages are configured yet, but it's a start

Improve messages

---

src/blueprint/ReviewerError.ts
src/handlers/events/delivery/scan/review/OnPendingScanStatus.ts
src/handlers/events/delivery/scan/review/checkstyle/checkstyleReviewer.ts
test/handlers/events/delivery/review/checkstyle/checkstyleReviewerTest.ts

When CheckStyle fails to run at all, throw an error. (of a specific class)
Catch these in the reviewer-runner, in OnPendingScanStatus; accumulate them along with the reviews, and report them, and require approval if any happened.

reviewer errors

---

src/blueprint/SoftwareDeliveryMachine.ts
src/common/goals/Goal.ts
src/handlers/commands/RetryDeploy.ts
src/handlers/events/delivery/build/BuildOnPendingBuildStatus.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnSuccessStatus.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnSuccessStatus1.ts
src/handlers/events/delivery/deploy/k8s/NoticeK8sDeployCompletion.ts
src/handlers/events/delivery/deploy/k8s/NoticeK8sProdDeployCompletion.ts
src/handlers/events/delivery/deploy/k8s/RequestK8sDeployOnSuccessStatus.ts
src/handlers/events/delivery/deploy/k8s/RequestK8sDeployOnSuccessStatus1.ts
src/handlers/events/delivery/goals/httpServiceGoals.ts
src/handlers/events/delivery/scan/fingerprint/FingerprintOnPendingStatus.ts
src/handlers/events/delivery/verify/OnEndpointStatus.ts
src/handlers/events/delivery/verify/approvalGate.ts
src/software-delivery-machine/blueprint/deploy/cloudFoundryDeploy.ts
src/software-delivery-machine/blueprint/deploy/dispose.ts
src/software-delivery-machine/blueprint/deploy/k8sDeploy.ts
src/software-delivery-machine/blueprint/deploy/localSpringBootDeployOnSuccessStatus.ts
src/software-delivery-machine/cloudFoundrySoftwareDeliveryMachine.ts
test/handlers/events/delivery/deploy/deployFromLocalTest.ts

No handler should know about all goals, merely check that current goal's preconditions are met.

Remove knowledge of all goals in handlers

---

src/common/goals/Goal.ts
src/handlers/events/delivery/build/FindArtifactOnImageLinked.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnSuccessStatus.ts
src/handlers/events/delivery/deploy/ExecuteGoalOnSuccessStatus.ts
src/handlers/events/delivery/scan/review/OnPendingAutofixStatus.ts
src/handlers/events/delivery/verify/OnEndpointStatus.ts
src/software-delivery-machine/cloudFoundrySoftwareDeliveryMachine.ts

- Makes preconditions more sophisticated, distinguishing between error and pending.
- Improves cosmetics of artifact goal rendering

Improve preconditions

---

.gitignore
package-lock.json
src/util/github/ghub.ts

this is all a kluge that will go away with custom-event Goals. Fixes #215

Fix ' at ' on build messages

---

src/blueprint/SoftwareDeliveryMachine.ts
src/common/delivery/code/autofix/executeAutofixes.ts
src/handlers/commands/editors/editorWrappers.ts
src/handlers/events/delivery/ExecuteGoalOnPendingStatus.ts
src/software-delivery-machine/blueprint/code/autofix/addAtomistHeader.ts
src/software-delivery-machine/blueprint/deploy/cloudFoundryDeploy.ts
src/software-delivery-machine/cloudFoundrySoftwareDeliveryMachine.ts
src/util/git/confirmEditedness.ts

fixes #217 
this works, i saw it work

one commit per autofix

---

package-lock.json
package.json
src/blueprint/SoftwareDeliveryMachine.ts
src/common/delivery/code/autofix/executeAutofixes.ts
src/software-delivery-machine/blueprint/code/autofix/addAtomistHeader.ts
src/software-delivery-machine/commands/editors/demo/removeTypeScriptHeader.ts

Revert on autofix failure

---

src/common/delivery/code/autofix/executeAutofixes.ts
src/common/delivery/deploy/deploy.ts
src/common/delivery/deploy/executeDeploy.ts
src/common/delivery/goals/Goal.ts
src/common/delivery/goals/common/commonGoals.ts
src/common/delivery/goals/storeGoals.ts
src/graphql/fragment/SdmGoalFields.graphql
src/handlers/events/delivery/ExecuteGoalOnRequested.ts
src/handlers/events/delivery/ExecuteGoalOnSuccessStatus.ts
src/handlers/events/delivery/build/FindArtifactOnImageLinked.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/deploy/k8s/NoticeK8sDeployCompletion.ts
src/handlers/events/delivery/deploy/k8s/NoticeK8sProdDeployCompletion.ts
src/handlers/events/delivery/verify/OnEndpointStatus.ts
src/ingesters/goal.ts

The first move toward updating goals instead of statuses.
The quantity of changes is about renames to move goal description customization in line with Goal states.
There's also a fix for the part where autofixes weren't being run.

begin updating goals

---

src/handlers/events/delivery/ExecuteGoalOnRequested.ts
src/handlers/events/delivery/ExecuteGoalOnSuccessStatus.ts

whitespace and dashes aren't allowed. Gotta start with a letter
this is for GraphQL
The prior behavior was "no error, just don't work"

Try to make the name passed in work as a subscription

---

src/software-delivery-machine/commands/editors/pcf/addCloudFoundryManifest.ts

I don't know whether this caused any problems for @johnsonr in his tests last night, but it can't belong here

pretty sure we don't want to be lifecycle

---

package-lock.json
package.json
src/common/delivery/deploy/pcf/CloudFoundryApi.ts
src/common/delivery/deploy/pcf/CloudFoundryPushDeployer.ts
src/common/delivery/deploy/pcf/CloudFoundryPusher.ts

use the deployment artifact cwd to find jar
make route a random host name like push can

final fixes for Spring apps to work with CF deploy

---

src/blueprint/SoftwareDeliveryMachine.ts
src/common/delivery/code/review/executeReview.ts
src/common/delivery/deploy/deploy.ts
src/common/delivery/deploy/executeDeploy.ts
src/common/delivery/goals/CopyGoalToGitHubStatus.ts
src/common/delivery/goals/common/commonGoals.ts
src/common/delivery/goals/fetchGoalsOnCommit.ts
src/common/delivery/goals/storeGoals.ts
src/graphql/subscription/OnBuildComplete.graphql
src/graphql/subscription/OnBuildCompleteForDryRun.graphql
src/graphql/subscription/OnImageLinked.graphql
src/handlers/events/delivery/ExecuteGoalOnRequested.ts
src/handlers/events/delivery/build/FindArtifactOnImageLinked.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/deploy/k8s/RequestK8sDeploys.ts
src/handlers/events/delivery/goals/SetGoalsOnPush.ts
src/handlers/events/delivery/verify/executeVerifyEndpoint.ts
src/ingesters/sdmGoalIngester.ts
src/software-delivery-machine/machines/k8sMachine.ts
src/software-delivery-machine/parts/team/commonTypeScriptErrors.ts

this is on top of my other PR, merge it first please
Fix this review to show sourceLocation, and all reviews to show a valid link if there is none

Review fixes

---

package-lock.json
package.json
src/software-delivery-machine/machines/generatorConfig.ts

The actual fix for this was in `automation-client-ts`: https://github.com/atomist/automation-client-ts/commit/f3f4f80821fc36a6efcb6421a6d1b10c88e2d48e
fixes #278

Install atomist webhook on new repos if no org hook exists

---

src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts

in lifecycle, we were showing snippets that are useless https://atomist-community.slack.com/archives/C7GHDARGU/p1522883778000398

Do nothing on build if we don't have a build goal

---

package-lock.json
src/common/delivery/build/local/maven/MavenBuilder.ts
src/common/delivery/deploy/pcf/CloudFoundryApi.ts
src/common/delivery/deploy/pcf/CloudFoundryBlueGreenDeployer.ts
src/common/delivery/deploy/pcf/CloudFoundryBlueGreener.ts
src/common/delivery/deploy/pcf/CloudFoundryPusher.ts
src/common/delivery/deploy/pcf/ProjectArchiver.ts

implements #199, but doesn't switch the deployer implementation yet

Blue green PCF deployment

---

src/common/delivery/build/local/LocalBuilder.ts

I can't tell whether this is the cause of the mask you're seeing but it could definitely have masked some

Fix one place where a failure could be masked

---

src/blueprint/SoftwareDeliveryMachine.ts

this caused the projectCreationMachine to fail to load

undefined is not an FU

---

src/common/delivery/build/local/SpawnBuilder.ts
src/common/delivery/build/local/lein/leinBuilder.ts
src/common/delivery/build/local/npm/NpmDetectBuildMapping.ts
src/common/delivery/build/local/npm/npmBuilder.ts
src/index.ts

logFactory was no longer used
artifactStore is optional

make SpawnBuilder take a parameter object

---

src/common/listener/support/PushRule.ts
test/common/listener/pushRuleTest.ts

nothing was using the push test.

Use push test

---

src/common/delivery/goals/Goal.ts
src/common/delivery/goals/common/MessageGoal.ts
src/common/delivery/goals/common/commonGoals.ts
src/common/delivery/goals/common/npmGoals.ts
src/common/delivery/goals/storeGoals.ts
src/ingesters/sdmGoalIngester.ts
test/blueprint/sdmGoalImplementationTest.ts
test/common/delivery/goals/goalTest.ts
test/handlers/events/delivery/ExecuteGoalTest.ts

Make naming consistent between SdmGoal and Goal

Consistent goal naming

---

src/common/delivery/build/local/SpawnBuilder.ts
src/common/delivery/build/local/lein/leinBuilder.ts
src/common/delivery/build/local/npm/executePublish.ts
src/util/misc/spawned.ts
test/util/misc/spawnedTest.ts

Explanatory Typedoc on spawn and SpawnBuilder

---

src/common/delivery/build/local/LocalBuilder.ts
src/common/delivery/build/local/SpawnBuilder.ts
src/common/delivery/goals/support/reportGoalError.ts
src/handlers/events/delivery/goals/executeGoal.ts

print less to the progress log, but more information in case of failure

More careful error printing

---

package-lock.json
package.json
src/common/log/RolarProgressLog.ts
test/common/log/RolarProgressLogTest.ts

test uses generators for getting next Date for log timestamp and creating repeatable Dates that are comparable in the asserts
isAvailable() is fixed
write automatically flushes to limit memory consumption
timestamp has more uniform formatting

add test for rolar logger and fixed several issues

---

src/common/delivery/deploy/local/jar/executableJarDeployer.ts
src/common/delivery/deploy/local/maven/mavenSourceDeployer.ts
src/common/delivery/deploy/pcf/CommandLineCloudFoundryDeployer.ts
src/common/log/DelimitedWriteProgressLogDecorator.ts
src/common/log/RolarProgressLog.ts
test/common/log/DelimitedWriteProgressLogDecoratorTest.ts
test/common/log/RolarProgressLogTest.ts

use it in the places where a child process writes its log out

separate delimited log logic  as a decorator

---

src/blueprint/SoftwareDeliveryMachine.ts
src/graphql/subscription/OnAnyFailedlSdmGoal.graphql
src/handlers/events/delivery/goals/SkipDownstreamGoalsOnGoalFailure.ts

this was still trying to use statuses, oops

Fix SkipDownstreamOnFailed

---

src/handlers/events/repo/OnFirstPushToRepo.ts

I found this when investigating why topics weren't being created on new repos when running smoke tests. The committer "atomist-bot" did not have a person//screenname in the event, and actions were silently uninvoked (including creating topics).
fixes atomist/sdm-smoke-test#9

the actions should not require a screen name to run

---

src/api-helper/command/generator/generatorCommand.ts
src/api-helper/goal/chooseAndSetGoals.ts
src/api-helper/goal/executeGoal.ts
src/api-helper/goal/reportGoalError.ts
src/api-helper/goal/storeGoals.ts
src/api-helper/machine/addWellKnownGoals.ts
src/handlers/commands/disposeCommand.ts
src/handlers/events/delivery/build/FindArtifactOnImageLinked.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
src/handlers/events/delivery/goals/RequestDownstreamGoalsOnGoalSuccess.ts
src/handlers/events/delivery/goals/SetGoalsOnPush.ts
src/handlers/events/delivery/goals/SkipDownstreamGoalsOnGoalFailure.ts
src/handlers/events/delivery/goals/resetGoals.ts
src/internal/delivery/deploy/deploy.ts
src/internal/delivery/goals/support/fetchGoalsOnCommit.ts
test/blueprint/sdmGoalImplementationTest.ts
test/handlers/events/delivery/ExecuteGoalTest.ts

Goal setting logic should be distinct from event handler implementations to maximize potential reuse and for clarity.

Separate goal setting logic from handlers

---

package-lock.json
package.json
src/api-helper/goal/executeGoal.ts
src/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
src/internal/machine/configureSdm.ts
src/util/misc/time.ts

This will gives us nice and useful goal and goal execution info in the logs, especially when viewed via rolar.

Add goal detail to progress log

---

src/api-helper/goal/executeGoal.ts
src/api-helper/log/LoggingProgressLog.ts
src/internal/delivery/build/local/LocalBuilder.ts
src/log/RolarProgressLog.ts
src/pack/pcf/CloudFoundryApi.ts
src/util/misc/spawned.ts

More error reporting from failed goals

---

src/handlers/events/delivery/goals/FulfillGoalOnRequested.ts
src/handlers/events/delivery/goals/RequestDownstreamGoalsOnGoalSuccess.ts
src/handlers/events/delivery/goals/RespondOnGoalCompletion.ts
src/handlers/events/delivery/goals/SkipDownstreamGoalsOnGoalFailure.ts
src/internal/delivery/goals/support/validateGoal.ts
test/internal/delivery/goals/support/validateGoalTest.ts

This lets us run multiple SDMs in the same workspace concurrently without interfering with each other on goal management and execution.

Select goals based on provenance

---

CHANGELOG.md
src/api-helper/command/transform/chattyEditor.ts
src/api-helper/machine/handlerRegistrations.ts
src/api/command/target/TransformModeSuggestion.ts
src/api/registration/CodeInspectionRegistration.ts
src/api/registration/CodeTransformRegistration.ts
src/api/registration/CommandRegistration.ts
src/api/registration/GeneratorRegistration.ts
src/pack/build-aware-transform/support/makeBuildAware.ts

Editors advise again when not doing anything

Restore chatty editor

---

legal/THIRD_PARTY.md
src/api-helper/listener/executeAutofixes.ts
test/api-helper/listener/executeAutofixesTest.ts

Filter autofix which just fixed code

---

src/api-helper/command/generator/generatorCommand.ts
src/api-helper/machine/handlerRegistrations.ts
src/api-helper/machine/projectLoaderRepoLoader.ts
src/api-helper/project/CachingProjectLoader.ts
src/api-helper/project/LazyProjectLoader.ts
test/api-helper/project/cachingProjectLoaderTest.ts
test/api-helper/project/lazyProjectLoaderTest.ts

- Using read only mode when possible in project operations
- Introduced `CachingProjectLoader`

Performance improvements in project operations

---

package-lock.json
package.json
src/api-helper/goal/executeGoal.ts

Just a tweak to avoid printing the world
once the client PR is merged this can move back to client's master branch

Avoid printing axios response chunder

---

package-lock.json
package.json

meant to put this on the last one

Master of client

---

CHANGELOG.md
src/api-helper/listener/executeReview.ts
src/api-helper/machine/ListenerRegistrationManagerSupport.ts
src/api/machine/ListenerRegistrationManager.ts
src/api/registration/ReviewListenerRegistration.ts
test/api-helper/listener/executeReviewTest.ts

Helps in diagnostics. Also makes review listener invocation more robust.

Review listeners must now be named

---

src/api-helper/misc/git/filesChangedSince.ts

I don't know how to fix #328 but we can ask for more information

Print more on diff error

---

src/api-helper/misc/git/filesChangedSince.ts

at least it does print when the error occurs

Fix incorrect print statement

---

src/api-helper/goal/DefaultGoalImplementationMapper.ts
src/api-helper/misc/result.ts
src/api/goal/Goal.ts
src/api/goal/common/AutoCodeInspection.ts
src/api/goal/common/Autofix.ts
src/api/goal/common/Build.ts
src/api/goal/common/Fingerprint.ts
src/api/goal/common/GenericGoal.ts
src/api/goal/common/MessageGoal.ts
src/api/goal/common/PushImpact.ts
src/api/machine/wellKnownGoals.ts
src/pack/well-known-goals/commonGoals.ts
test/api-helper/misc/result.test.ts
test/api/dsl/goalContribution.test.ts

[atomist:generated] [atomist:autofix=tslint]

Autofix: tslint

---

lib/api-helper/misc/extensionPack.ts
lib/api/machine/ExtensionPack.ts
test/api-helper/misc/extensionPack.test.ts

Add tags to ExtensionPack metadata

---

lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api-helper/machine/ListenerRegistrationManagerSupport.ts
lib/api/machine/ListenerRegistrationManager.ts
lib/api/machine/SoftwareDeliveryMachine.ts

"Well-known" goals should be set at per instance level, not per SDM level.

Remove SDM-level goal methods

---

lib/api-helper/goal/executeGoal.ts
lib/api-helper/goal/mock.ts
lib/api-helper/testsupport/fakePush.ts
test/api-helper/goal/executeGoal.test.ts
test/api-helper/goal/mock.test.ts

Add mock support

---

lib/api/goal/GoalWithFulfillment.ts
lib/api/goal/common/createGoal.ts
package-lock.json

Adds the ability to wrap a goal to wait for a precondition and keep trying. For example, this would allow deployment of one service to wait on deployment of another. Unlike a PushTest, this will keep trying for a specified time.

Add createPredicatedGoal

---

lib/api-helper/goal/executeDeploy.ts
lib/api-helper/goal/executeGoal.ts
lib/api-helper/goal/executeUndeploy.ts
lib/api-helper/listener/createPushImpactListenerInvocation.ts
lib/api-helper/listener/executeAutoInspects.ts
lib/api-helper/listener/executeAutofixes.ts
lib/api-helper/listener/executeCancel.ts
lib/api-helper/listener/executeFingerprinting.ts
lib/api-helper/listener/executePushImpact.ts
lib/api-helper/listener/executeVerifyEndpoint.ts
lib/api-helper/project/GitHubLazyProjectLoader.ts
lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
lib/api/goal/GoalInvocation.ts
lib/spi/project/LazyProjectLoader.ts
test/api-helper/goal/executeGoal.test.ts
test/api-helper/listener/executeAutoInspect.test.ts
test/api-helper/listener/executeAutofixes.test.ts
test/api-helper/listener/executeCancel.test.ts
test/api-helper/project/GitHubLazyProjectLoader.test.ts
test/api/goal/GoalWithFulfillment.test.ts

and fix the materialization if LazyProjects before running goal implementations on them.
And fix a lot of deprecation warnings.

Introduce LazyProjectLoader and LazyProject interfaces

---

lib/api/command/target/GitlabRepoTargets.ts

Adds Gitlab repo targets for commands

---

lib/api-helper/command/generator/generatorCommand.ts

This helps with Getting Started

Provide the URL to the local SDM so it can give instructions

---

lib/api-helper/project/withProject.ts

This is useful when you want a ProjectAwareGoalInvocation but do not
want an ExecuteGoal.
Per https://github.com/atomist/docs-sdm/blob/08e0c738f35d21cd2bd87faa1b354a30c4b0dd98/lib/machine/htmltest.ts#L88

Add project-aware goal invocation converter

---

lib/api-helper/command/transform/codeTransformWrapping.ts
lib/api-helper/listener/executeAutoInspects.ts
lib/api-helper/machine/adaptHandleCommand.ts
lib/api-helper/machine/handlerRegistrations.ts
lib/api/registration/PushAwareParametersInvocation.ts
test/api-helper/machine/adaptHandleCommand.test.ts

Add progressLog to CodeInspection and CodeTransform

---

lib/api/goal/Goal.ts
lib/api/goal/GoalWithFulfillment.ts
package-lock.json

this function is exported, although I don't think its used anywhere else
On principle I deprecated it, if you'd rather delete it go for it.

Fix typo in spelling

---

lib/api-helper/goal/executeGoal.ts

If the goal executor is successful, return the result from it,
ensuring the code is 0 to retain backward compatibility.  This should
help with atomist/sdm-core#206.

Return goal result from executeGoal

---

lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api-helper/project/CachingProjectLoader.ts
lib/api-helper/project/support/cacheKey.ts
package-lock.json
package.json
test/api-helper/project/cachingProjectLoader.test.ts

CachingProjectLoader should respect clone parameters

---

lib/api-helper/goal/chooseAndSetGoals.ts
lib/api-helper/goal/executeGoal.ts
lib/api-helper/listener/createPushImpactListenerInvocation.ts
lib/api-helper/listener/executeAutoInspects.ts
lib/api-helper/machine/handlerRegistrations.ts
lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
lib/api-helper/testsupport/fakeCommandListenerInvocation.ts
lib/api-helper/testsupport/fakeGoalInvocation.ts
lib/api-helper/testsupport/fakePush.ts
lib/api/context/SdmContext.ts
lib/api/context/skillContext.ts
lib/api/mapping/goalTest.ts
lib/api/mapping/outputTest.ts
lib/graphql/schema.json
lib/graphql/subscription/OnAnySkillOutput.graphql
test/api/context/skillContext.test.ts
test/api/mapping/predictGoals.ts

Hook the `SkillOutput` type into the goal caching infrastructure and provide a test to assert on `SkillOutput` events to trigger new goals.

Add support for skill output

---

lib/api-helper/goal/DefaultGoalImplementationMapper.ts
lib/api-helper/goal/chooseAndSetGoals.ts
lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api/goal/support/GoalImplementationMapper.ts

Provide default values for goal side effect registration and push
test.

Default registration and push test for side effect
