atomist/sdm

package-lock.json
package.json
src/handlers/commands/RetryDeploy.ts
src/handlers/events/delivery/artifact/local/LocalArtifactStore.ts
src/handlers/events/delivery/build/BuildOnScanSuccessStatus.ts
src/handlers/events/delivery/build/Builder.ts
src/handlers/events/delivery/build/local/LocalBuilder.ts
src/handlers/events/delivery/build/local/maven/MavenBuilder.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnFingerprint.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnImageLinked.ts
src/handlers/events/delivery/deploy/Deployer.ts
src/handlers/events/delivery/deploy/deploy.ts
src/handlers/events/delivery/deploy/local/maven/mavenDeployer.ts
src/handlers/events/delivery/log/InterpretedLog.ts
src/handlers/events/delivery/log/NaiveLinkablePersistentProgressLog.ts
src/handlers/events/delivery/log/ProgressLog.ts
src/sdm/AbstractSoftwareDeliveryMachine.ts
src/software-delivery-machine/SpringPCFSoftwareDeliveryMachine.ts
src/util/reportFailureInterpretation.ts

Deployers and local builders have the option to interpret the logs, deciding whether to display the full log as a snippet.
and for local deploys, add a Retry button.

Show logs in Slack on deploy and build failures

---

src/handlers/events/delivery/FailDownstreamPhasesOnPhaseFailure.ts
src/handlers/events/delivery/Phases.ts
src/handlers/events/delivery/build/BuildOnScanSuccessStatus.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnFingerprint.ts
src/handlers/events/delivery/deploy/DeployFromLocalOnImageLinked.ts
src/handlers/events/delivery/deploy/OnDeployStatus.ts
src/handlers/events/delivery/deploy/deploy.ts
src/handlers/events/delivery/phase/OnSuperseded.ts
src/handlers/events/delivery/phase/SetSupersededStatus.ts
src/handlers/events/delivery/phase/SetupPhasesOnPush.ts
src/handlers/events/delivery/phases/core.ts
src/handlers/events/delivery/phases/gitHubContext.ts
src/handlers/events/delivery/phases/httpServicePhases.ts
src/handlers/events/delivery/phases/libraryPhases.ts
src/handlers/events/delivery/phases/productionDeployPhases.ts
src/handlers/events/delivery/review/WithCodeOnPendingScanStatus.ts
src/handlers/events/delivery/verify/OnVerifiedStatus.ts
src/handlers/events/delivery/verify/VerifyOnEndpointStatus.ts
src/handlers/events/gates/StatusApprovalGate.ts
src/sdm/AbstractSoftwareDeliveryMachine.ts
src/software-delivery-machine/SpringPCFSoftwareDeliveryMachine.ts
src/software-delivery-machine/blueprint/build/LocalMavenBuildOnScanSuccessStatus.ts
src/software-delivery-machine/blueprint/deploy/deployToProd.ts
test/handlers/events/delivery/PhasesTest.ts

This branch has some useful fixes on it, like making tests run at all
The meaningful change is to gameOver: it parses the pending statuses to find the ones to update instead of using the hard-coded list.
I wanted to show the idea of, working from the plan as it is laid out on the commit (in GH statuses), instead of from the hard-coded list of phases.
The idea is, the plan could be modified. Scan could decide to add an extra verification step, or something. The goal is to decouple (to some degree) the decision of what to do, from the doing of it. It's more event-y.
There are other places still working from the hard-coded list but this is a start.

More eventy: determine subsequent steps dynamically

---

README.md
src/handlers/commands/editors/toclient/ghub.ts
src/handlers/events/delivery/ArtifactStore.ts
src/handlers/events/delivery/artifact/github/GitHubReleaseArtifactStore.ts
src/handlers/events/delivery/artifact/local/LocalArtifactStore.ts
src/handlers/events/delivery/build/local/LocalBuilder.ts
src/handlers/events/delivery/deploy/Deployer.ts
src/handlers/events/delivery/deploy/deploy.ts
src/handlers/events/delivery/deploy/pcf/CloudFoundryTarget.ts
src/handlers/events/delivery/deploy/pcf/CommandLineCloudFoundryDeployer.ts
src/handlers/events/delivery/phase/SetupPhasesOnPush.ts
src/sdm/AbstractSoftwareDeliveryMachine.ts
src/software-delivery-machine/SpringPCFSoftwareDeliveryMachine.ts
src/software-delivery-machine/blueprint/phase/phaseManagement.ts
src/software-delivery-machine/commands/editors/addCloudFoundryManifest.ts

Behaves the same as master, but makes changes necessary to be able to switch to the new `GitHubReleaseArtifactStore`.
*Note this new implementation is not presently working, because asset upload to a GitHub release is failing.*
- Adds GitHub tag and release code
- Adds GitHub `ArtifactStore` implementation
- Changes various signatures to pass GitHub credentials
- Cleans up a leaky abstraction in command line Cloud Foundry deployer, which relied on a local directory being present already
- Switch to builder pattern in `AbstractSoftwareDeliveryMachine` for `supportingCommands`
- Started documentation in readme

Begin work to switch to GitHub releases for storing artifacts

---

src/handlers/events/delivery/Phases.ts
src/handlers/events/delivery/build/BuildOnScanSuccessStatus.ts
src/handlers/events/delivery/build/local/LocalBuilder.ts
src/handlers/events/delivery/build/local/maven/MavenBuilder.ts
src/software-delivery-machine/SpringPCFSoftwareDeliveryMachine.ts
src/software-delivery-machine/blueprint/build/LocalMavenBuildOnScanSuccessStatus.ts

This way the logs for the build appear with their correlation ID.
Also there is not a dependency on ordering of the "exit" handlers on a childProcess.
It's still a bit weird. It returns a promise (of a running build) containing a promise (of a completed build). This is OK.
please squash

let build finish before returning

---

src/blueprint/SoftwareDeliveryMachine.ts
src/common/phases/Phases.ts
src/handlers/events/delivery/FailDownstreamPhasesOnPhaseFailure.ts
src/handlers/events/delivery/phases/httpServicePhases.ts

This gets the phases off the commit, then takes all later ones (by convention in context) that are pending and sets them to failed.

Make one FailDownstream work for all

---

package-lock.json
package.json
src/blueprint/SoftwareDeliveryMachine.ts
src/common/slack/addressChannels.ts
src/handlers/events/delivery/verify/OnEndpointStatus.ts

When an endpoint verification fails, it posts a message now, with a Retry button. When pushed, that command calls the verification again.
It doesn't yet update the message when you push the button. That is not ideal, but we can live with it for now. At least we have a way to retry.

retry verify

---

src/handlers/commands/reportRunning.ts
src/handlers/events/delivery/deploy/deploy.ts
src/software-delivery-machine/blueprint/deploy/describeRunningServices.ts
src/util/slack/reportFailureInterpretation.ts

@cdupuis Merge this and you'll get better diagnostics. The whole thing doesn't work for me, but this way if it doesn't find the endpoint it'll ship you the log so you can debug it.
It's trying to find the endpoint in the log with this grammar: https://github.com/atomist/github-sdm/blob/b3deec7f928c3ac8e0059d04bbcef4e22c8ab1b8/src/handlers/events/delivery/deploy/pcf/cloudFoundryLogParser.ts#L21-25

When endpoint not found in CF deploy, print log

---

src/software-delivery-machine/springSdmConfig.ts

This doesn't really belong in spring config either, I don't think? 
but really, it should be general: we should be able to trigger any goal set.
... which is not urgent, so for now, here's a tiny bit of confusion avoided.

applyHttpServiceGoals is not an editor

---

src/common/delivery/deploy/pcf/CloudFoundryApi.ts
src/common/delivery/deploy/pcf/CloudFoundryPushDeployer.ts
src/common/delivery/deploy/pcf/CloudFoundryPusher.ts

This jar size was larger than anything that I deployed before and I had to get around the default size limit.
I used the new project loader rather than cloning the project myself. This give me access to the jar so that I don't have to build it again.
If there is a filename specified in the DeployableArtifact, then use that as an archive.
small fix for when no services are specified in the manifest.yml.

fix some remaining issues with deploying a spring app.

---

src/blueprint/SoftwareDeliveryMachine.ts
src/common/delivery/deploy/deploy.ts
src/common/delivery/deploy/executeDeploy.ts
src/common/delivery/goals/CopyGoalToGitHubStatus.ts
src/common/delivery/goals/common/commonGoals.ts
src/common/delivery/goals/fetchGoalsOnCommit.ts
src/common/delivery/goals/storeGoals.ts
src/graphql/subscription/OnBuildComplete.graphql
src/graphql/subscription/OnBuildCompleteForDryRun.graphql
src/graphql/subscription/OnImageLinked.graphql
src/handlers/events/delivery/ExecuteGoalOnRequested.ts
src/handlers/events/delivery/build/FindArtifactOnImageLinked.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/deploy/k8s/RequestK8sDeploys.ts
src/handlers/events/delivery/goals/SetGoalsOnPush.ts
src/handlers/events/delivery/verify/executeVerifyEndpoint.ts
src/ingesters/sdmGoalIngester.ts
src/software-delivery-machine/machines/k8sMachine.ts

OK. This takes out the rest of the createStatus calls with a few exceptions:
- k8-automation communication needs reworked, so I didn't change that. We want it to trigger directly off of goals
- editor dry run continues to run with statuses
- Superseded is a status, that's a separate problem

most of status updates are goals

---

src/software-delivery-machine/blueprint/deploy/cloudFoundryDeploy.ts

tested this with a locally running sdm and some minor modifications to make it work.
It still deploys the losgatos spring project.

Switch PCF deployer to API implementation

---

src/software-delivery-machine/blueprint/deploy/cloudFoundryDeploy.ts

closes #199 
I tested this several different ways in the actual application by running the goals. I ran into a few problems with getting it to run, but the main one was a 422 on app start because our PCF account was out of memory.
I'd like to modify the retry for that http call to give more info about the error in the log, and also not actually retry in that case.

Use blue green deployer

---

package-lock.json
package.json
src/common/log/progressLogs.ts

This adds a dependency to [s3-streamlogger](https://www.npmjs.com/package/s3-streamlogger) and a ProgressLog based on it. This is one of the most widely used s3 logging libs and it automatically handles incrementally flushing to the files and rotating the logs. It integrates well with winston which is a popular js logging framework. We aren't using winston directly, but already have a dependency on it. It helps format the logs in a consistent way with timestamps. Right now, the logger is configured with the console and s3 stream transports. This allows logs to both places at the same time with a similar structure.
console:
```
2018-04-10T19:12:37.252Z - info: Updating app with manifest development:hello-express-new.
2018-04-10T19:12:37.767Z - info: Starting …
```

add s3 ProgressLog

---

src/common/delivery/build/local/lein/leinBuilder.ts
src/common/listener/support/pushtest/jvm/jvmPushTests.ts
src/common/log/S3ProgressLog.ts
src/ingesters/sdmVersionIngester.ts
src/software-delivery-machine/machines/cloudFoundryMachine.ts
test/handlers/events/delivery/build/local/lein/packageCljTest.ts

Needs to be integrated with ArtifactStore and to parse build output to interpret it. But successfully builds `automation-client-clj`. Relies on lean being installed on automation client node.

Initial Lein build support

---

src/common/log/S3ProgressLog.ts

These are the assumptions that the Rolar project makes about reading the logs.
It may be too constraining to hardcode the bucket name, but I can't imagine anyone wanting to change it and configure AWS buckets and user permissions.

standardize the location and format of the s3 logs

---

src/common/log/RolarProgressLog.ts
test/common/log/RolarProgressLogTest.ts

Now it is possible to make the logs look as intended from a child process. With this config it leaves off the timestamp and log level and buffers the writes until a newline is encountered at the end of the message.
```
const infoLog = new RolarProgressLog("http://fakehost", ["test"], "\n", 10000, "info", null);
const errorLog = new RolarProgressLog("http://fakehost", ["test"], "\n", 10000, "error", null);
childProcess.stdout.on("data", what => infoLog.write(buffer));
childProcess.stderr.on("data", what => errorLog.write(buffer));
```

Rolar logging for child process

---

src/common/delivery/build/local/lein/leinBuilder.ts
src/common/delivery/build/local/maven/mavenLogInterpreter.ts
src/common/delivery/build/local/npm/npmLogInterpreter.ts
src/common/delivery/deploy/local/maven/mavenSourceDeployer.ts
src/common/delivery/deploy/pcf/CloudFoundryBlueGreenDeployer.ts
src/common/delivery/deploy/pcf/CloudFoundryPushDeployer.ts
src/common/delivery/deploy/pcf/CommandLineCloudFoundryDeployer.ts
src/common/delivery/goals/support/logInterpreters.ts
src/util/slack/reportFailureInterpretationToLinkedChannels.ts
test/util/slack/reportFailureInterpretationTest.ts

This removes all the places we were saying to please show the log
Instead if the log has a URL it will skip it, and if it does not,
we will send it to Slack as a snippet.
That way if Rolar is down we'll get the log in slack by default.
the log interpreters can still explicitly include or not include it.

If the log is available online, don't show it

---

src/common/delivery/code/autofix/executeAutofixes.ts

Write to the progress log instead of logger.info; this gets to the same place and also Rolar (if enabled)
This brings up the point that we want to pass the progressLog into all Listeners. Not there yet.

Write to progress log in autofixes

---

src/common/delivery/build/local/npm/npmLogInterpreter.ts
src/handlers/events/delivery/build/SetStatusOnBuildComplete.ts
src/handlers/events/delivery/goals/executeGoal.ts
src/util/slack/reportFailureInterpretationToLinkedChannels.ts

parse logs on pre-goal-hook failure
label failures from external builds differently (this could be the cause of too many snippets, we'll be able to tell)
if no interpretation, do the same default thing of sending the log only if there's no URL
and more logging about these logs.
If this doesn't fix the excessive snippetiness it should tell me more

some better logging logic

---

src/common/command/editor/dry-run/dryRunEditor.ts
src/common/command/editor/editorCommand.ts

Allows BitBucket to be used for editors

Pass in targets parameters to editors

---

CHANGELOG.md
src/internal/delivery/build/local/npm/executePublish.ts

Add tag as option when publishing a Node.js package using NPM.  Make
optional NPM publish options optional and only add them if they are
provided.  Use a package-local .npmrc rather than overwriting and then
deleting the user's .npmrc.
Remove errorFinder that reimplements the default.
Closes #404

Can now provide tag when running NPM publish

---

package-lock.json
package.json
src/internal/delivery/build/local/npm/executePublish.ts

This way we won't update the `latest` tag unless we specifically request it in the NpmOptions.

publish should default to tagging by branch

---

src/api-helper/log/DelimitedWriteProgressLogDecorator.ts
src/api-helper/log/LoggingProgressLog.ts
test/api-helper/log/DelimitedWriteProgressLogDecoratorTest.ts
test/api-helper/log/LoggingProgressLogTest.ts

The DelimitedWrite progress log decorator postpones writes until the end of a line.
It should still pass on the delimiter though!
This was causing the build logs to all be one line when analyzed for slack messaging, which made them unparsable.
Please can we have the newlines back downstream.

Restore newlines on writing each line

---

src/api-helper/machine/handlerRegistrations.ts
src/api/registration/CommandRegistration.ts
src/api/registration/GeneratorRegistration.ts
test/api/registration/commandRegistrationTest.ts

Backward compatible. Adds a builder option for parameter declaration. Allow parameters to be added to existing decorated parameter classes, or either approach used on its own.

Add builder option for declaring command parameters

---

src/api/mapping/support/PushRule.ts
src/api/mapping/support/pushTestUtils.ts

This causes very subtle bugs when people happen to name different tests with the same name.
If we have an expensive pushTest, people can memoize it explicitly.

Do not memoize pre-emptively

---

CHANGELOG.md
src/api-helper/command/editor/localCommandsCodeTransform.ts
src/api-helper/machine/handlerRegistrations.ts
src/api/registration/AutofixRegistration.ts
src/api/registration/ProjectOperationRegistration.ts

- `CodeTransform` defaults to `SimpleProjectEditor`, the commonest case
- Autofixes can use multiple transforms to be consistent with transform and generator registrations

Autofixes can use many transforms

---

CHANGELOG.md
package-lock.json
src/api-helper/command/generator/generatorCommand.ts
src/api-helper/machine/handlerRegistrations.ts
src/api/registration/CommandHandlerRegistration.ts
src/api/registration/GeneratorRegistration.ts
src/api/registration/ParametersDefinition.ts
test/api/registration/commandRegistrationTest.ts

- It's no longer necessary to specify a type extending `SeedDrivenGeneratorParameters` to create a parameter.  This is consistent with how editor registrations already worked.
- Parameters added using `parameters` property of `CommandRegistration` can have default values.
For example, it's now possible to define a generator like this:
```typescript
sdm.addGeneratorCommand<{param: string}({
name: "typescript-express-generator",
startingPoint: new GitHubRepoRef("spring-team", "typescript-express-seed"),
intent: "create node",
parameters: {
param: { required: false, defaultValue: "thing" },
},
transform: [
UpdatePackageJsonIdentification,
UpdateReadmeTitle],
})
```
This change is backward compatible.

Generators no longer require base parameters

---

src/api/goal/Goals.ts
test/api/goal/GoalsTest.ts

This allows to create `Goals` instances without the tedious deconstruction etc:
```
const StagingDeploymentGoals = goals("Simple Goals")
.plan(ReviewGoal)
.plan(BuildGoal, AutofixGoal).after(ReviewGoal)
.plan(StagingEndpointGoal).after(BuildGoal)
.plan(ProductionDeploymentGoal).after(BuildGoal, StagingEndpointGoal);
```

Add DSL for creating Goals

---

CHANGELOG.md
src/api-helper/command/editor/editorCommand.ts
src/api-helper/command/generator/generatorCommand.ts
src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
src/api-helper/machine/HandlerRegistrationManagerSupport.ts
src/api-helper/machine/handlerRegistrations.ts
src/api-helper/test/README.md
src/api-helper/test/fakeCommandListenerInvocation.ts
src/api-helper/test/fakeContext.ts
src/api-helper/test/fakeGoalInvocation.ts
src/api-helper/test/fakePush.ts
src/api/machine/CommandRegistrationManager.ts
src/api/machine/SoftwareDeliveryMachineOptions.ts
src/api/registration/CodeInspectionRegistration.ts
src/api/registration/CodeTransformRegistration.ts
src/api/registration/GeneratorRegistration.ts
test/api-helper/listener/executeAutofixesTest.ts
test/api-helper/listener/executePushReactionsTest.ts
test/api-helper/listener/executeReviewTest.ts

- Add `CodeInspection` to run non-mutating functions against repos
- Correct bug affecting all project operation commands where targeting parameters could bleed through into next command

Add CodeInspection

---

CHANGELOG.md
src/api-helper/machine/handlerRegistrations.ts
src/api/command/target/TransformModeSuggestion.ts
src/api/registration/CodeInspectionRegistration.ts
src/api/registration/CodeTransformRegistration.ts
src/api/registration/CommandRegistration.ts
src/api/registration/GeneratorRegistration.ts
src/pack/build-aware-transform/support/makeBuildAware.ts

- No longer extends `automation-client` command hierarchy, offering more control in `sdm`
- `editMode` now `TransformMode` and provides access to both SdmContext and project

Transform command improvement

---

src/api/mapping/support/PredicateMappingCostAnalyzer.ts
src/api/mapping/support/defaultPredicateMappingCostAnalyzer.ts
src/api/mapping/support/predicateUtils.ts
src/api/mapping/support/projectPredicateUtils.ts
src/api/mapping/support/pushTestUtils.ts
test/api/mapping/support/projectPredicateUtilsTest.ts
test/api/mapping/support/pushTestUtilsTest.ts

Optimizes push test by inspecting the code to see how they're implemented. Effectively gives short circuit evaluation while preserving parallelization.

Add predicate mapping cost analyzer

---

CHANGELOG.md
src/api/dsl/goalContribution.ts
src/api/goal/Goals.ts
src/api/machine/wellKnownGoals.ts
test/api/dsl/goalContributionTest.ts
tslint.json

Add the special `LockingGoal` to the goal set, or call `Goals.andLock()`

Add ability to lock Goals in contribution model

---

src/graphql/query/ReposInTeam.graphql

because all graphql fields are optional, all the types match up fine,
and DefaultRepoRefResolver in sdm-core expects these fields, but they're
not in the query here.
This prevents targets.repos selection from working at all on transforms

Get enough data to  find the repo

---

src/api-helper/project/CachingProjectLoader.ts

hey @cdupuis that cleanup-after-10-seconds raised some warning flags in my head, because some operations can take that long, and it would be really hard to figure out why the operation crashed in that case. How about we log that at a higher level than if we have reason to believe we're done?

Specific logging on cleanup of cached project

---

CHANGELOG.md
src/api-helper/listener/executeAutofixes.ts
src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
src/api-helper/machine/handlerRegistrations.ts
src/api/machine/SoftwareDeliveryMachine.ts
src/api/project/exports.ts
src/api/registration/AutofixRegistration.ts
src/api/registration/CodeInspectionRegistration.ts
src/api/registration/CodeTransformRegistration.ts
src/api/registration/ProjectInvariantRegistration.ts
src/api/registration/PushRegistration.ts
test/api-helper/TestSoftwareDeliveryMachine.ts
test/api-helper/listener/executeAutofixesTest.ts
tslint.json

Introduces new registration that can function as a transform, inspection and autofix, naturally expressing the notion of a project invariant.
Built on lower level concepts.
Required renaming of the `react` methods on `CodeTransformRegistration` and `CodeInspectionRegistration` and `parameters` on `AutofixRegistration` to avoid conflict. This renaming is an improvement, as it's clearer.

Add project invariant concept

---

CHANGELOG.md
package.json
src/api-helper/code/review/patternMatchReviewer.ts
src/api-helper/listener/executeAutoInspects.ts
src/api-helper/listener/executeReview.ts
src/api-helper/machine/ListenerRegistrationManagerSupport.ts
src/api/listener/ParametersInvocation.ts
src/api/machine/ListenerRegistrationManager.ts
src/api/registration/AutoInspectRegistration.ts
src/api/registration/AutoInspectionRegistration.ts
src/api/registration/CodeInspectionRegistration.ts
src/api/registration/CodeTransform.ts
src/api/registration/PushImpactListenerRegistration.ts
src/api/registration/ReviewerRegistration.ts
test/api-helper/code/review/patternMatchReviewerTest.ts
test/api-helper/listener/executeAutoInspectTest.ts
test/api-helper/listener/executeReviewTest.ts

- Adds an `AutoInspectRegistration`. `ReviewRegistration` is now a specialization of this.
- Parameters are now available to auto inspections and reviews
- Autofixes and auto inspect/reviewers no longer take misleading `CommandListenerInvocation` but new `ParametersInvocation`
- Added `onInspectionResult` method for auto inspect/reviewers

Add AutoInspect registration

---

package-lock.json
package.json
src/api-helper/goal/DefaultGoalImplementationMapper.ts
src/api-helper/goal/chooseAndSetGoals.ts
src/api-helper/listener/createPushImpactListenerInvocation.ts
src/api-helper/listener/executeAutoInspects.ts
src/api-helper/listener/executeAutofixes.ts
src/api-helper/listener/executeFingerprinting.ts
src/api-helper/listener/executePushReactions.ts
src/api-helper/misc/git/filesChangedSince.ts
src/api-helper/project/cloningProjectLoader.ts
src/api-helper/test/fakeGoalInvocation.ts
src/api/goal/Goal.ts
src/spi/project/ProjectLoader.ts
test/api-helper/misc/git/filesChangedSince.test.ts
test/api-helper/project/lazyProjectLoader.test.ts

This now checks the list of commits on the push and passes this + 1 as depth down to the cloning support in order to be able to correctly determine the list of changed files. 
This fixes #481, #328, #293

Pass depth down to `git clone` in order to correctly diff the changes

---

lib/api-helper/goal/executeBuild.ts
lib/api-helper/goal/executeGoal.ts
lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
lib/api/goal/GoalInvocation.ts
lib/api/goal/GoalWithFulfillment.ts
lib/api/goal/support/GoalImplementationMapper.ts
lib/api/machine/GoalDrivenMachine.ts
lib/api/mapping/support/commonPushTests.ts
lib/spi/build/Builder.ts
package-lock.json
test/api-helper/goal/executeGoal.test.ts

This allows us to attach listeners to Goals that get called whenever a project is cloned etc. This will let us populate project resources from caches and consistently apply things like compilation before running the actual goal on the project.

Support code level project listeners

---

lib/api-helper/goal/executeDeploy.ts
lib/graphql/fragment/PushFields.graphql
lib/graphql/query/CommitForSdmGoal.graphql

Add the newer images link to commits.  The image link was not removed,
so this is backward compatible.  Update usage of image link to images
in deployer.
Closes #96

Add commit-images link to GraphQL

---

lib/api/machine/WellKnownGoals.ts

Add a type that can be used by extension packs that work with well known goals. Intended to help create consistency between extension packs and naming within SDM instances.
Using naming in `sdm-pack-spring` and `sdm-pack-node`.

Add WellKnownGoals

---

lib/api-helper/goal/executeGoal.ts
lib/api-helper/goal/storeGoals.ts
lib/api-helper/listener/executeAutoInspects.ts
lib/api-helper/log/DelimitedWriteProgressLogDecorator.ts
lib/api-helper/log/EphemeralProgressLog.ts
lib/api-helper/log/StringCapturingProgressLog.ts
lib/api-helper/log/WriteToAllProgressLog.ts
lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api-helper/misc/git/GitHubIssueRouter.ts
lib/api-helper/project/LazyProjectLoader.ts
lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
lib/api-helper/testsupport/fakeContext.ts
lib/api/context/AdminCommunicationContext.ts
lib/api/context/addressChannels.ts
lib/api/goal/common/AutoCodeInspection.ts
lib/api/goal/common/Fingerprint.ts
lib/api/listener/StartupListener.ts
lib/api/registration/AutoInspectRegistration.ts
lib/api/registration/CodeInspectionRegistration.ts
lib/api/registration/CodeTransformRegistration.ts
lib/spi/build/Builder.ts
lib/spi/deploy/Deployer.ts
lib/spi/issue/IssueRouter.ts
lib/spi/log/ProgressLog.ts
package-lock.json
test/api-helper/listener/executeAutoInspect.test.ts
test/api-helper/log/DelimitedWriteProgressLogDecorator.test.ts

Certain types and functions--e.g. `AddressChannels`--returned `Promise<any>`. This could result in unexpected errors: For example, a `CodeTransform` that returned `sdmContext.addressChannels(message)` would cause a failure in editor infrastructure.
The impact of this change on user code should be minor and fairly clear. It feels like a worthwhile tightening before 1.0.0.GA.

Replace `Promise<any>` with `Promise<void>`

---

lib/api-helper/goal/executeGoal.ts
lib/api/goal/ExecuteGoalResult.ts
test/api-helper/goal/executeGoal.test.ts
test/api/goal/ExecuteGoalResult.test.ts

Omitting `code` means `success`as does `code: 0`.

Make `code` on `ExecuteGoalResult` optional

---

lib/api/mapping/GoalSetter.ts
lib/api/mapping/support/PushRules.ts

Previously we ran all PushMappings in parallel which means that expensive PushTests would get executed even though we might already have an ealier result.

Run PushMappings sequentially

---

lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api-helper/machine/ListenerRegistrationManagerSupport.ts
lib/api/listener/TriggeredListener.ts
lib/api/machine/ListenerRegistrationManager.ts
lib/api/registration/TriggeredListenerRegistration.ts
package-lock.json
package.json
test/api-helper/machine/AbstractSoftwareDeliveryMachine.test.ts

Allows to register listeners that run based on configured intervals in milliseconds or cron patterns.

Add support for trigger listeners

---

lib/api-helper/goal/chooseAndSetGoals.ts
lib/api-helper/goal/storeGoals.ts
lib/api-helper/listener/goalSetListener.ts
lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api/goal/SdmGoalSetMessage.ts
lib/api/goal/common/Queue.ts
lib/api/goal/common/createGoal.ts
lib/graphql/query/InProcessSdmGoalSets.graphql
lib/graphql/query/SdmGoalByGoalSetIdAndUniqueName.graphql
lib/graphql/query/SdmGoalSetForId.graphql
lib/graphql/schema.json
lib/graphql/subscription/OnAnySdmGoalSet.graphql
test/api-helper/goal/storeGoals.test.ts
test/api/goal/common/Queue.test.ts
test/api/goal/common/createGoal.test.ts

The Queue maintains a queue of goals sets of configurable size. Once a goal set is terminated, the queue goal will trigger the next waiting goal sets, etc.
I also fixed a couple of bugs in the `waitRules` and missing state on `SdmGoalSet`.

Add `Queue` goal to queue goal sets

---

lib/api-helper/command/transform/spawnCodeTransform.ts
lib/api-helper/goal/executeGoal.ts
lib/api-helper/misc/child_process.ts
lib/api-helper/project/withProject.ts
test/api-helper/misc/child_process.test.ts
test/api-helper/project/withProject.test.ts

Rather than have a separate log argument, just make the log option
property not optional.  Update code throughout.

Provide spawnLog with consistent spawn interface

---

lib/api/dsl/goalContribution.ts
lib/api/dsl/goalDsl.ts
test/api/dsl/goalContribution.test.ts

When evaluating contributor-style push rules, ordering is guaranteed. And efficiency can often be improved by only performing expensive computations once. 
This PR allows state to be added to the `PushListenerInvocation` used within this push rule computation mode and referenced in subsequent push rules, for greater efficiency.

Allow state computation in push rule evaluation

---

lib/api/dsl/goalContribution.ts
test/api/dsl/goalContribution.test.ts

Also tighten typing.
Not a breaking change as this new functionality has not been released.

Rename enrichInvocation to attachFact

---

lib/api/command/target/BitBucketRepoTargets.ts
lib/api/command/target/GitHubRepoTargets.ts
package-lock.json
package.json

Add `targets.branch` to `CodeTransform` targeting parameter classes. 
The actual support for this is mostly in atomist/automation-client#434.

Add `targets.branch` to `CodeTransform` targeting

---

lib/api/machine/ListenerRegistrationManager.ts

this is what I notice from looking at the code. It doesn't change for "ready" or "approved" etc

Update doc on goal execution listener

---

lib/api-helper/project/cloningProjectLoader.ts

The trigger for this is because we should have the SHA available in code inspections.
It is possible this will change something elsewhere. It seems like this is
useful to have generally. If it does cause problems, we could move it to only
do this on code inspections.

Populate the SHA on projects when loading them.

---

lib/api-helper/listener/executeAutofixes.ts

This puts output to the log in the case that one of the git commands fails. Otherwise, that output is completely munched, and I can't tell why a commit failed.

If an autofix error includes some output, print it to the progress log

---

lib/api-helper/machine/handlerRegistrations.ts
lib/api/registration/CommandRegistration.ts
lib/api/registration/ParametersDefinition.ts
test/api/registration/commandRegistration.test.ts

Ensure that definitions must match parameter types, avoiding potential errors. Consider this registration:
```typescript
const reg: CommandHandlerRegistration<{ foo: string, bar: string }> = {
name: "test",
parameters: {
foo: {},
bar: {},
},
...
};
```
This change ensures that the names of the properties of the `parameters` field matches the names of the type of the parameters.

Use TypeScript Record type to enforce matching of parameter interface with definitions

---

lib/api/goal/support/GoalLauncher.ts
lib/api/machine/SoftwareDeliveryMachineOptions.ts
package-lock.json
package.json

This PR introduces an improved extension point for launching goals. Several `GaolLauncher` instances can be registered; the first which `supports` method returns `true` will `launch` the goal.
This is a change in public API, but I don't expect anybody to have implemented a custom `IsolatedGoalLauncher` at this point.

Make goal launching more pluggable

---

lib/api-helper/command/generator/generatorCommand.ts
lib/api-helper/machine/handlerRegistrations.ts
lib/api/registration/GeneratorRegistration.ts

1. Enable a function startingPoint for a generator registration to access the command listener invocation.
2. Enable the use of parameter gathering continuations in a startingPoint function.
Backward compatible.

Improve startingPoint handling in generators

---

lib/api-helper/listener/executeAutoInspects.ts
lib/api/goal/common/AutoCodeInspection.ts

The autoinspect goal logs had no useful info. Before:
after this PR:
(this is with an SDM from the spring-seed, and the GitHubIssue review listener fails because the repo is a fork. But now, I get to see what is happening in the log, and also see the review comments that it could not send to GitHub.

Print statuses for each inspection in the AutoInspect goal

---

lib/api-helper/command/transform/onTransformResult.ts

This is one way to get some notification when the save failed.
the story is: I made a transform with a colon in its name. When I ran it, it told me it was successful, because it didn't fail to edit the project. But it did fail to save those edits to a branch! It did not tell me!
Also it does not tell the branch when it succeeds; I have to go looking for it.
With this implementation of onTransformResults, I get a message in case of failure or success. It's very useful, I have wanted this a dozen times, and so it should be available in the library.

Provide a useful implementation of onTransformResults

---

lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
lib/api/registration/CommandRegistration.ts

This enables command registrations to be suppressed based on environment variables or SDM configuration.
This enables experimental features to be tried within one codebase without automatic exposure to all users.

Add conditional command registration

---

lib/api/registration/PushImpactListenerRegistration.ts

Corrects an error in PushImpactListener registration. Previously it was impossible to return void from such a listener, which was undesirable. Also the types were incorrect in returning a response code.

Clean up push impact invocation

---

lib/api-helper/command/generator/generatorCommand.ts
lib/api-helper/listener/executeAutofixes.ts
lib/api-helper/machine/handlerRegistrations.ts
lib/api/goal/common/Autofix.ts
lib/api/listener/CommandListener.ts
lib/api/registration/CodeTransformRegistration.ts
lib/api/registration/GeneratorRegistration.ts
test/api-helper/listener/executeAutofixes.test.ts

Also adds capabilities to run `ProjectAction` as `afterActions` on generators.
fixes #687, fixes #714

Allow transform presentation on autofix goal

---

lib/api-helper/code/fingerprint/AbstractFingerprint.ts
lib/api-helper/misc/sha.ts

Throwing a more specific error is better than getting "cannot find property `length` of undefined" from js-sha

Fingerprint data is required

---

package-lock.json
package.json

Apply policy `typescript-version::typescript-version`:
**New TypeScript Version Policy**
Policy version for TypeScript is `^3.5.3`.
Project *atomist/sdm/master* is currently using version `^3.5.2`.
_TypeScript Version_
```TypeScript version (^3.5.3)```
---
<details>
<summary>Tags</summary>
<br/>
<code>[atomist:generated]</code><br/><code>[auto-branch-delete:on-close]</code><br/><code>[auto-merge-method:squash]</code><br/><code>[auto-merge:on-approve]</code><br/><code>[fingerprint:typescript-version::typescript-version=65546ea5b01bb62f7b74c5d027cb8128f7cda8d5ae207501c0666411a403612d]</code>
</details>

Apply policy for TypeScript version

---

lib/api-helper/machine/handlerRegistrations.ts
test/api-helper/machine/handlerRegistration.test.ts

Hi, 
I saw this open issue on the backlog and created a pull-request to resolve it. 
Could you provide some feedback on changes that I would need in order to get this merge in?
Additional info:
- the ruleset is based on the [git-check-ref-format man page](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html)
- I had to export the gitBranchCompatible function in order to test it, is there a better approach?

Resolves #669

---

lib/api-helper/machine/handlerRegistrations.ts
lib/api-helper/project/GitHubLazyProjectLoader.ts
lib/api-helper/project/fileCopy.ts
lib/api/listener/CommandListener.ts
lib/api/registration/CommandRegistration.ts
package-lock.json
package.json

Closes #793 
This PR adds:
- Support to use RegExp as intents
- Attaches a new `matches` property to the `CommandListenerInvocation` that is a `RegExpExecArray` that contains the raw intent that was typed along with the matches to the intent regex (if it was supplied)
- ~~Depends on https://github.com/atomist/automation-client/pull/637~~
- ~~Will update package.json once 637 is merged~~

Support RegExp Intents and retrieving parameters from them.

---

lib/api-helper/goal/sdmGoal.ts
lib/api-helper/misc/child_process.ts
lib/api-helper/misc/spawned.ts
lib/core/pack/k8s/container.ts
lib/core/pack/k8s/scheduler/KubernetesGoalScheduler.ts
lib/core/pack/k8s/sync/startup.ts
test/core/pack/k8s/container.test.ts
test/core/pack/k8s/scheduler/KubernetesGoalScheduler.test.ts

The first container in container goals will exit when the SDM goal
timeout is exceeded.  This does not kill the pod.  Add a check for
this case in the job cleanup logic.  Increase frequency of job
cleanup.  Centralize lookup of SDM goal timeout and job TTL.
Only record pod spec in KubernetesGoalScheduler.
Do not perform sync in isolated goals.
Towards #816 #815

Kill timed out container goals

---

lib/core/pack/k8s/deploy/deploy.ts
lib/core/pack/k8s/deploy/externalUrls.ts
lib/core/pack/k8s/kubernetes/deployment.ts
lib/core/pack/k8s/kubernetes/ingress.ts
lib/core/pack/k8s/kubernetes/namespace.ts
lib/core/pack/k8s/kubernetes/patch.ts
lib/core/pack/k8s/kubernetes/request.ts
lib/core/pack/k8s/kubernetes/role.ts
lib/core/pack/k8s/kubernetes/roleBinding.ts
lib/core/pack/k8s/kubernetes/secret.ts
lib/core/pack/k8s/kubernetes/service.ts
lib/core/pack/k8s/kubernetes/serviceAccount.ts
test/core/pack/k8s/deploy/externalUrls.test.ts
test/core/pack/k8s/kubernetes/deployment.test.ts
test/core/pack/k8s/kubernetes/ingress.test.ts
test/core/pack/k8s/kubernetes/patch.test.ts

Allow setting of patch strategy in the KubernetesApplication interface. Remove single-use properties that are only proxies for values that can be provided in the various partial specs.

K8s patch strategy and simplify KubernetesApplication

---

lib/core/pack/k8s/sync/repo.ts
lib/core/pack/k8s/sync/startup.ts
test/core/pack/k8s/sync/repo.test.ts

Some credentials expire, so when a k8s sync repo interval is
configured, query the credentials from the graph prior to each sync.
Towards #828

Query for credentials each k8s repo sync
